language: php

cache:
    directories:
        $HOME/.composer/cache/files

php:
    - 7.0

install:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer update
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer require satooshi/php-coveralls

script:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer lint
    - composer test -- --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php -n vendor/bin/coveralls
